language: python

env:
    - TOX_ENV=py34-dj18
    - TOX_ENV=py33-dj18
    - TOX_ENV=py32-dj18
    - TOX_ENV=py27-dj18
    - TOX_ENV=py34-dj17
    - TOX_ENV=py33-dj17
    - TOX_ENV=py32-dj17
    - TOX_ENV=py27-dj17
    - TOX_ENV=py34-dj16
    - TOX_ENV=py33-dj16
    - TOX_ENV=py32-dj16
    - TOX_ENV=py27-dj16
    - TOX_ENV=py26-dj16
    - TOX_ENV=py27-djmaster
    - TOX_ENV=py32-djmaster
    - TOX_ENV=py33-djmaster
    - TOX_ENV=py34-djmaster

matrix:
  fast_finish: true
  allow_failures:
    - env: TOX_ENV=py27-djmaster
    - env: TOX_ENV=py32-djmaster
    - env: TOX_ENV=py33-djmaster
    - env: TOX_ENV=py34-djmaster

before_install:
  - pip install codecov

install:
  - pip install -r requirements-test.txt

script:
  - tox -e $TOX_ENV

after_success:
  - codecov
