language: python

env:
    - TOX_ENV=py26-dj16-sqlite-unittest
    - TOX_ENV=py26-dj16-sqlite-nose
    - TOX_ENV=py26-dj16-postgres-unittest
    - TOX_ENV=py26-dj16-postgres-nose
    - TOX_ENV=py26-dj16-mysql-unittest
    - TOX_ENV=py26-dj16-mysql-nose
    - TOX_ENV=py27-dj13-sqlite-unittest
    - TOX_ENV=py27-dj13-sqlite-nose
    - TOX_ENV=py27-dj13-postgres-unittest
    - TOX_ENV=py27-dj13-postgres-nose
    - TOX_ENV=py27-dj13-mysql-unittest
    - TOX_ENV=py27-dj13-mysql-nose
    - TOX_ENV=py27-dj14-sqlite-unittest
    - TOX_ENV=py27-dj14-sqlite-nose
    - TOX_ENV=py27-dj14-postgres-unittest
    - TOX_ENV=py27-dj14-postgres-nose
    - TOX_ENV=py27-dj14-mysql-unittest
    - TOX_ENV=py27-dj14-mysql-nose
    - TOX_ENV=py27-dj15-sqlite-unittest
    - TOX_ENV=py27-dj15-sqlite-nose
    - TOX_ENV=py27-dj15-postgres-unittest
    - TOX_ENV=py27-dj15-postgres-nose
    - TOX_ENV=py27-dj15-mysql-unittest
    - TOX_ENV=py27-dj15-mysql-nose
    - TOX_ENV=py27-dj16-sqlite-unittest
    - TOX_ENV=py27-dj16-sqlite-nose
    - TOX_ENV=py27-dj16-postgres-unittest
    - TOX_ENV=py27-dj16-postgres-nose
    - TOX_ENV=py27-dj16-mysql-unittest
    - TOX_ENV=py27-dj16-mysql-nose
    - TOX_ENV=py27-dj17-sqlite-unittest
    - TOX_ENV=py27-dj17-sqlite-nose
    - TOX_ENV=py27-dj17-postgres-unittest
    - TOX_ENV=py27-dj17-postgres-nose
    - TOX_ENV=py27-dj17-mysql-unittest
    - TOX_ENV=py27-dj17-mysql-nose
    - TOX_ENV=py27-dj18-sqlite-unittest
    - TOX_ENV=py27-dj18-sqlite-nose
    - TOX_ENV=py27-dj18-postgres-unittest
    - TOX_ENV=py27-dj18-postgres-nose
    - TOX_ENV=py27-dj18-mysql-unittest
    - TOX_ENV=py27-dj18-mysql-nose
    - TOX_ENV=py27-dj19-sqlite-unittest
    - TOX_ENV=py27-dj19-sqlite-nose
    - TOX_ENV=py27-dj19-postgres-unittest
    - TOX_ENV=py27-dj19-postgres-nose
    - TOX_ENV=py27-dj19-mysql-unittest
    - TOX_ENV=py27-dj19-mysql-nose
    - TOX_ENV=py27-dj110-sqlite-unittest
    - TOX_ENV=py27-dj110-sqlite-nose
    - TOX_ENV=py27-dj110-postgres-unittest
    - TOX_ENV=py27-dj110-postgres-nose
    - TOX_ENV=py27-dj110-mysql-unittest
    - TOX_ENV=py27-dj110-mysql-nose
    - TOX_ENV=py27-dj111-sqlite-unittest
    - TOX_ENV=py27-dj111-sqlite-nose
    - TOX_ENV=py27-dj111-postgres-unittest
    - TOX_ENV=py27-dj111-postgres-nose
    - TOX_ENV=py27-dj111-mysql-unittest
    - TOX_ENV=py27-dj111-mysql-nose
    - TOX_ENV=py32-dj13-sqlite-unittest
    - TOX_ENV=py32-dj13-sqlite-nose
    - TOX_ENV=py32-dj13-postgres-unittest
    - TOX_ENV=py32-dj13-postgres-nose
    - TOX_ENV=py32-dj13-mysql-unittest
    - TOX_ENV=py32-dj13-mysql-nose
    - TOX_ENV=py32-dj14-sqlite-unittest
    - TOX_ENV=py32-dj14-sqlite-nose
    - TOX_ENV=py32-dj14-postgres-unittest
    - TOX_ENV=py32-dj14-postgres-nose
    - TOX_ENV=py32-dj14-mysql-unittest
    - TOX_ENV=py32-dj14-mysql-nose
    - TOX_ENV=py32-dj15-sqlite-unittest
    - TOX_ENV=py32-dj15-sqlite-nose
    - TOX_ENV=py32-dj15-postgres-unittest
    - TOX_ENV=py32-dj15-postgres-nose
    - TOX_ENV=py32-dj15-mysql-unittest
    - TOX_ENV=py32-dj15-mysql-nose
    - TOX_ENV=py32-dj16-sqlite-unittest
    - TOX_ENV=py32-dj16-sqlite-nose
    - TOX_ENV=py32-dj16-postgres-unittest
    - TOX_ENV=py32-dj16-postgres-nose
    - TOX_ENV=py32-dj16-mysql-unittest
    - TOX_ENV=py32-dj16-mysql-nose
    - TOX_ENV=py32-dj17-sqlite-unittest
    - TOX_ENV=py32-dj17-sqlite-nose
    - TOX_ENV=py32-dj17-postgres-unittest
    - TOX_ENV=py32-dj17-postgres-nose
    - TOX_ENV=py32-dj17-mysql-unittest
    - TOX_ENV=py32-dj17-mysql-nose
    - TOX_ENV=py32-dj18-sqlite-unittest
    - TOX_ENV=py32-dj18-sqlite-nose
    - TOX_ENV=py32-dj18-postgres-unittest
    - TOX_ENV=py32-dj18-postgres-nose
    - TOX_ENV=py32-dj18-mysql-unittest
    - TOX_ENV=py32-dj18-mysql-nose
    - TOX_ENV=py32-dj110-sqlite-unittest
    - TOX_ENV=py32-dj110-sqlite-nose
    - TOX_ENV=py32-dj110-postgres-unittest
    - TOX_ENV=py32-dj110-postgres-nose
    - TOX_ENV=py32-dj110-mysql-unittest
    - TOX_ENV=py32-dj110-mysql-nose
    - TOX_ENV=py32-dj111-sqlite-unittest
    - TOX_ENV=py32-dj111-sqlite-nose
    - TOX_ENV=py32-dj111-postgres-unittest
    - TOX_ENV=py32-dj111-postgres-nose
    - TOX_ENV=py32-dj111-mysql-unittest
    - TOX_ENV=py32-dj111-mysql-nose
    - TOX_ENV=py33-dj13-sqlite-unittest
    - TOX_ENV=py33-dj13-sqlite-nose
    - TOX_ENV=py33-dj13-postgres-unittest
    - TOX_ENV=py33-dj13-postgres-nose
    - TOX_ENV=py33-dj13-mysql-unittest
    - TOX_ENV=py33-dj13-mysql-nose
    - TOX_ENV=py33-dj14-sqlite-unittest
    - TOX_ENV=py33-dj14-sqlite-nose
    - TOX_ENV=py33-dj14-postgres-unittest
    - TOX_ENV=py33-dj14-postgres-nose
    - TOX_ENV=py33-dj14-mysql-unittest
    - TOX_ENV=py33-dj14-mysql-nose
    - TOX_ENV=py33-dj15-sqlite-unittest
    - TOX_ENV=py33-dj15-sqlite-nose
    - TOX_ENV=py33-dj15-postgres-unittest
    - TOX_ENV=py33-dj15-postgres-nose
    - TOX_ENV=py33-dj15-mysql-unittest
    - TOX_ENV=py33-dj15-mysql-nose
    - TOX_ENV=py33-dj16-sqlite-unittest
    - TOX_ENV=py33-dj16-sqlite-nose
    - TOX_ENV=py33-dj16-postgres-unittest
    - TOX_ENV=py33-dj16-postgres-nose
    - TOX_ENV=py33-dj16-mysql-unittest
    - TOX_ENV=py33-dj16-mysql-nose
    - TOX_ENV=py33-dj17-sqlite-unittest
    - TOX_ENV=py33-dj17-sqlite-nose
    - TOX_ENV=py33-dj17-postgres-unittest
    - TOX_ENV=py33-dj17-postgres-nose
    - TOX_ENV=py33-dj17-mysql-unittest
    - TOX_ENV=py33-dj17-mysql-nose
    - TOX_ENV=py33-dj18-sqlite-unittest
    - TOX_ENV=py33-dj18-sqlite-nose
    - TOX_ENV=py33-dj18-postgres-unittest
    - TOX_ENV=py33-dj18-postgres-nose
    - TOX_ENV=py33-dj18-mysql-unittest
    - TOX_ENV=py33-dj18-mysql-nose
    - TOX_ENV=py33-dj110-sqlite-unittest
    - TOX_ENV=py33-dj110-sqlite-nose
    - TOX_ENV=py33-dj110-postgres-unittest
    - TOX_ENV=py33-dj110-postgres-nose
    - TOX_ENV=py33-dj110-mysql-unittest
    - TOX_ENV=py33-dj110-mysql-nose
    - TOX_ENV=py33-dj111-sqlite-unittest
    - TOX_ENV=py33-dj111-sqlite-nose
    - TOX_ENV=py33-dj111-postgres-unittest
    - TOX_ENV=py33-dj111-postgres-nose
    - TOX_ENV=py33-dj111-mysql-unittest
    - TOX_ENV=py33-dj111-mysql-nose
    - TOX_ENV=py34-dj13-sqlite-unittest
    - TOX_ENV=py34-dj13-sqlite-nose
    - TOX_ENV=py34-dj13-postgres-unittest
    - TOX_ENV=py34-dj13-postgres-nose
    - TOX_ENV=py34-dj13-mysql-unittest
    - TOX_ENV=py34-dj13-mysql-nose
    - TOX_ENV=py34-dj14-sqlite-unittest
    - TOX_ENV=py34-dj14-sqlite-nose
    - TOX_ENV=py34-dj14-postgres-unittest
    - TOX_ENV=py34-dj14-postgres-nose
    - TOX_ENV=py34-dj14-mysql-unittest
    - TOX_ENV=py34-dj14-mysql-nose
    - TOX_ENV=py34-dj15-sqlite-unittest
    - TOX_ENV=py34-dj15-sqlite-nose
    - TOX_ENV=py34-dj15-postgres-unittest
    - TOX_ENV=py34-dj15-postgres-nose
    - TOX_ENV=py34-dj15-mysql-unittest
    - TOX_ENV=py34-dj15-mysql-nose
    - TOX_ENV=py34-dj16-sqlite-unittest
    - TOX_ENV=py34-dj16-sqlite-nose
    - TOX_ENV=py34-dj16-postgres-unittest
    - TOX_ENV=py34-dj16-postgres-nose
    - TOX_ENV=py34-dj16-mysql-unittest
    - TOX_ENV=py34-dj16-mysql-nose
    - TOX_ENV=py34-dj17-sqlite-unittest
    - TOX_ENV=py34-dj17-sqlite-nose
    - TOX_ENV=py34-dj17-postgres-unittest
    - TOX_ENV=py34-dj17-postgres-nose
    - TOX_ENV=py34-dj17-mysql-unittest
    - TOX_ENV=py34-dj17-mysql-nose
    - TOX_ENV=py34-dj18-sqlite-unittest
    - TOX_ENV=py34-dj18-sqlite-nose
    - TOX_ENV=py34-dj18-postgres-unittest
    - TOX_ENV=py34-dj18-postgres-nose
    - TOX_ENV=py34-dj18-mysql-unittest
    - TOX_ENV=py34-dj18-mysql-nose
    - TOX_ENV=py34-dj19-sqlite-unittest
    - TOX_ENV=py34-dj19-sqlite-nose
    - TOX_ENV=py34-dj19-postgres-unittest
    - TOX_ENV=py34-dj19-postgres-nose
    - TOX_ENV=py34-dj19-mysql-unittest
    - TOX_ENV=py34-dj19-mysql-nose
    - TOX_ENV=py34-dj110-sqlite-unittest
    - TOX_ENV=py34-dj110-sqlite-nose
    - TOX_ENV=py34-dj110-postgres-unittest
    - TOX_ENV=py34-dj110-postgres-nose
    - TOX_ENV=py34-dj110-mysql-unittest
    - TOX_ENV=py34-dj110-mysql-nose
    - TOX_ENV=py34-dj111-sqlite-unittest
    - TOX_ENV=py34-dj111-sqlite-nose
    - TOX_ENV=py34-dj111-postgres-unittest
    - TOX_ENV=py34-dj111-postgres-nose
    - TOX_ENV=py34-dj111-mysql-unittest
    - TOX_ENV=py34-dj111-mysql-nose
    - TOX_ENV=py35-dj13-sqlite-unittest
    - TOX_ENV=py35-dj13-sqlite-nose
    - TOX_ENV=py35-dj13-postgres-unittest
    - TOX_ENV=py35-dj13-postgres-nose
    - TOX_ENV=py35-dj13-mysql-unittest
    - TOX_ENV=py35-dj13-mysql-nose
    - TOX_ENV=py35-dj14-sqlite-unittest
    - TOX_ENV=py35-dj14-sqlite-nose
    - TOX_ENV=py35-dj14-postgres-unittest
    - TOX_ENV=py35-dj14-postgres-nose
    - TOX_ENV=py35-dj14-mysql-unittest
    - TOX_ENV=py35-dj14-mysql-nose
    - TOX_ENV=py35-dj15-sqlite-unittest
    - TOX_ENV=py35-dj15-sqlite-nose
    - TOX_ENV=py35-dj15-postgres-unittest
    - TOX_ENV=py35-dj15-postgres-nose
    - TOX_ENV=py35-dj15-mysql-unittest
    - TOX_ENV=py35-dj15-mysql-nose
    - TOX_ENV=py35-dj16-sqlite-unittest
    - TOX_ENV=py35-dj16-sqlite-nose
    - TOX_ENV=py35-dj16-postgres-unittest
    - TOX_ENV=py35-dj16-postgres-nose
    - TOX_ENV=py35-dj16-mysql-unittest
    - TOX_ENV=py35-dj16-mysql-nose
    - TOX_ENV=py35-dj17-sqlite-unittest
    - TOX_ENV=py35-dj17-sqlite-nose
    - TOX_ENV=py35-dj17-postgres-unittest
    - TOX_ENV=py35-dj17-postgres-nose
    - TOX_ENV=py35-dj17-mysql-unittest
    - TOX_ENV=py35-dj17-mysql-nose
    - TOX_ENV=py35-dj18-sqlite-unittest
    - TOX_ENV=py35-dj18-sqlite-nose
    - TOX_ENV=py35-dj18-postgres-unittest
    - TOX_ENV=py35-dj18-postgres-nose
    - TOX_ENV=py35-dj18-mysql-unittest
    - TOX_ENV=py35-dj18-mysql-nose
    - TOX_ENV=py35-dj19-sqlite-unittest
    - TOX_ENV=py35-dj19-sqlite-nose
    - TOX_ENV=py35-dj19-postgres-unittest
    - TOX_ENV=py35-dj19-postgres-nose
    - TOX_ENV=py35-dj19-mysql-unittest
    - TOX_ENV=py35-dj19-mysql-nose
    - TOX_ENV=py35-dj110-sqlite-unittest
    - TOX_ENV=py35-dj110-sqlite-nose
    - TOX_ENV=py35-dj110-postgres-unittest
    - TOX_ENV=py35-dj110-postgres-nose
    - TOX_ENV=py35-dj110-mysql-unittest
    - TOX_ENV=py35-dj110-mysql-nose
    - TOX_ENV=py35-dj111-sqlite-unittest
    - TOX_ENV=py35-dj111-sqlite-nose
    - TOX_ENV=py35-dj111-postgres-unittest
    - TOX_ENV=py35-dj111-postgres-nose
    - TOX_ENV=py35-dj111-mysql-unittest
    - TOX_ENV=py35-dj111-mysql-nose
    - TOX_ENV=py36-dj13-sqlite-unittest
    - TOX_ENV=py36-dj13-sqlite-nose
    - TOX_ENV=py36-dj13-postgres-unittest
    - TOX_ENV=py36-dj13-postgres-nose
    - TOX_ENV=py36-dj13-mysql-unittest
    - TOX_ENV=py36-dj13-mysql-nose
    - TOX_ENV=py36-dj14-sqlite-unittest
    - TOX_ENV=py36-dj14-sqlite-nose
    - TOX_ENV=py36-dj14-postgres-unittest
    - TOX_ENV=py36-dj14-postgres-nose
    - TOX_ENV=py36-dj14-mysql-unittest
    - TOX_ENV=py36-dj14-mysql-nose
    - TOX_ENV=py36-dj15-sqlite-unittest
    - TOX_ENV=py36-dj15-sqlite-nose
    - TOX_ENV=py36-dj15-postgres-unittest
    - TOX_ENV=py36-dj15-postgres-nose
    - TOX_ENV=py36-dj15-mysql-unittest
    - TOX_ENV=py36-dj15-mysql-nose
    - TOX_ENV=py36-dj16-sqlite-unittest
    - TOX_ENV=py36-dj16-sqlite-nose
    - TOX_ENV=py36-dj16-postgres-unittest
    - TOX_ENV=py36-dj16-postgres-nose
    - TOX_ENV=py36-dj16-mysql-unittest
    - TOX_ENV=py36-dj16-mysql-nose
    - TOX_ENV=py36-dj17-sqlite-unittest
    - TOX_ENV=py36-dj17-sqlite-nose
    - TOX_ENV=py36-dj17-postgres-unittest
    - TOX_ENV=py36-dj17-postgres-nose
    - TOX_ENV=py36-dj17-mysql-unittest
    - TOX_ENV=py36-dj17-mysql-nose
    - TOX_ENV=py36-dj18-sqlite-unittest
    - TOX_ENV=py36-dj18-sqlite-nose
    - TOX_ENV=py36-dj18-postgres-unittest
    - TOX_ENV=py36-dj18-postgres-nose
    - TOX_ENV=py36-dj18-mysql-unittest
    - TOX_ENV=py36-dj18-mysql-nose
    - TOX_ENV=py36-dj19-sqlite-unittest
    - TOX_ENV=py36-dj19-sqlite-nose
    - TOX_ENV=py36-dj19-postgres-unittest
    - TOX_ENV=py36-dj19-postgres-nose
    - TOX_ENV=py36-dj19-mysql-unittest
    - TOX_ENV=py36-dj19-mysql-nose
    - TOX_ENV=py36-dj110-sqlite-unittest
    - TOX_ENV=py36-dj110-sqlite-nose
    - TOX_ENV=py36-dj110-postgres-unittest
    - TOX_ENV=py36-dj110-postgres-nose
    - TOX_ENV=py36-dj110-mysql-unittest
    - TOX_ENV=py36-dj110-mysql-nose
    - TOX_ENV=py36-dj111-sqlite-unittest
    - TOX_ENV=py36-dj111-sqlite-nose
    - TOX_ENV=py36-dj111-postgres-unittest
    - TOX_ENV=py36-dj111-postgres-nose
    - TOX_ENV=py36-dj111-mysql-unittest
    - TOX_ENV=py36-dj111-mysql-nose

matrix:
  fast_finish: true
  allow_failures:
    - env: TOX_ENV=py32-dj13-sqlite-unittest
    - env: TOX_ENV=py32-dj13-sqlite-nose
    - env: TOX_ENV=py32-dj13-postgres-unittest
    - env: TOX_ENV=py32-dj13-postgres-nose
    - env: TOX_ENV=py32-dj13-mysql-unittest
    - env: TOX_ENV=py32-dj13-mysql-nose
    - env: TOX_ENV=py32-dj14-sqlite-unittest
    - env: TOX_ENV=py32-dj14-sqlite-nose
    - env: TOX_ENV=py32-dj14-postgres-unittest
    - env: TOX_ENV=py32-dj14-postgres-nose
    - env: TOX_ENV=py32-dj14-mysql-unittest
    - env: TOX_ENV=py32-dj14-mysql-nose
    - env: TOX_ENV=py32-dj15-sqlite-unittest
    - env: TOX_ENV=py32-dj15-sqlite-nose
    - env: TOX_ENV=py32-dj15-postgres-unittest
    - env: TOX_ENV=py32-dj15-postgres-nose
    - env: TOX_ENV=py32-dj15-mysql-unittest
    - env: TOX_ENV=py32-dj15-mysql-nose
    - env: TOX_ENV=py32-dj16-sqlite-unittest
    - env: TOX_ENV=py32-dj16-sqlite-nose
    - env: TOX_ENV=py32-dj16-postgres-unittest
    - env: TOX_ENV=py32-dj16-postgres-nose
    - env: TOX_ENV=py32-dj16-mysql-unittest
    - env: TOX_ENV=py32-dj16-mysql-nose
    - env: TOX_ENV=py32-dj17-sqlite-unittest
    - env: TOX_ENV=py32-dj17-sqlite-nose
    - env: TOX_ENV=py32-dj17-postgres-unittest
    - env: TOX_ENV=py32-dj17-postgres-nose
    - env: TOX_ENV=py32-dj17-mysql-unittest
    - env: TOX_ENV=py32-dj17-mysql-nose
    - env: TOX_ENV=py32-dj18-sqlite-unittest
    - env: TOX_ENV=py32-dj18-sqlite-nose
    - env: TOX_ENV=py32-dj18-postgres-unittest
    - env: TOX_ENV=py32-dj18-postgres-nose
    - env: TOX_ENV=py32-dj18-mysql-unittest
    - env: TOX_ENV=py32-dj18-mysql-nose
    - env: TOX_ENV=py32-dj110-sqlite-unittest
    - env: TOX_ENV=py32-dj110-sqlite-nose
    - env: TOX_ENV=py32-dj110-postgres-unittest
    - env: TOX_ENV=py32-dj110-postgres-nose
    - env: TOX_ENV=py32-dj110-mysql-unittest
    - env: TOX_ENV=py32-dj110-mysql-nose
    - env: TOX_ENV=py32-dj111-sqlite-unittest
    - env: TOX_ENV=py32-dj111-sqlite-nose
    - env: TOX_ENV=py32-dj111-postgres-unittest
    - env: TOX_ENV=py32-dj111-postgres-nose
    - env: TOX_ENV=py32-dj111-mysql-unittest
    - env: TOX_ENV=py32-dj111-mysql-nose
    - env: TOX_ENV=py35-dj13-sqlite-unittest
    - env: TOX_ENV=py35-dj13-sqlite-nose
    - env: TOX_ENV=py35-dj13-postgres-unittest
    - env: TOX_ENV=py35-dj13-postgres-nose
    - env: TOX_ENV=py35-dj13-mysql-unittest
    - env: TOX_ENV=py35-dj13-mysql-nose
    - env: TOX_ENV=py35-dj14-sqlite-unittest
    - env: TOX_ENV=py35-dj14-sqlite-nose
    - env: TOX_ENV=py35-dj14-postgres-unittest
    - env: TOX_ENV=py35-dj14-postgres-nose
    - env: TOX_ENV=py35-dj14-mysql-unittest
    - env: TOX_ENV=py35-dj14-mysql-nose
    - env: TOX_ENV=py35-dj15-sqlite-unittest
    - env: TOX_ENV=py35-dj15-sqlite-nose
    - env: TOX_ENV=py35-dj15-postgres-unittest
    - env: TOX_ENV=py35-dj15-postgres-nose
    - env: TOX_ENV=py35-dj15-mysql-unittest
    - env: TOX_ENV=py35-dj15-mysql-nose
    - env: TOX_ENV=py35-dj16-sqlite-unittest
    - env: TOX_ENV=py35-dj16-sqlite-nose
    - env: TOX_ENV=py35-dj16-postgres-unittest
    - env: TOX_ENV=py35-dj16-postgres-nose
    - env: TOX_ENV=py35-dj16-mysql-unittest
    - env: TOX_ENV=py35-dj16-mysql-nose
    - env: TOX_ENV=py35-dj17-sqlite-unittest
    - env: TOX_ENV=py35-dj17-sqlite-nose
    - env: TOX_ENV=py35-dj17-postgres-unittest
    - env: TOX_ENV=py35-dj17-postgres-nose
    - env: TOX_ENV=py35-dj17-mysql-unittest
    - env: TOX_ENV=py35-dj17-mysql-nose
    - env: TOX_ENV=py35-dj18-sqlite-unittest
    - env: TOX_ENV=py35-dj18-sqlite-nose
    - env: TOX_ENV=py35-dj18-postgres-unittest
    - env: TOX_ENV=py35-dj18-postgres-nose
    - env: TOX_ENV=py35-dj18-mysql-unittest
    - env: TOX_ENV=py35-dj18-mysql-nose
    - env: TOX_ENV=py35-dj19-sqlite-unittest
    - env: TOX_ENV=py35-dj19-sqlite-nose
    - env: TOX_ENV=py35-dj19-postgres-unittest
    - env: TOX_ENV=py35-dj19-postgres-nose
    - env: TOX_ENV=py35-dj19-mysql-unittest
    - env: TOX_ENV=py35-dj19-mysql-nose
    - env: TOX_ENV=py35-dj110-sqlite-unittest
    - env: TOX_ENV=py35-dj110-sqlite-nose
    - env: TOX_ENV=py35-dj110-postgres-unittest
    - env: TOX_ENV=py35-dj110-postgres-nose
    - env: TOX_ENV=py35-dj110-mysql-unittest
    - env: TOX_ENV=py35-dj110-mysql-nose
    - env: TOX_ENV=py35-dj111-sqlite-unittest
    - env: TOX_ENV=py35-dj111-sqlite-nose
    - env: TOX_ENV=py35-dj111-postgres-unittest
    - env: TOX_ENV=py35-dj111-postgres-nose
    - env: TOX_ENV=py35-dj111-mysql-unittest
    - env: TOX_ENV=py35-dj111-mysql-nose

before_install:
  - pip install codecov

install:
  - pip install -r requirements-test.txt

script:
  - tox -e $TOX_ENV


after_success:
  - coverage run --source django_fake_model runtests.py
  - codecov
