language: python

env:
    - TOX_ENV=py26-dj16-sqlite-unittest
    - TOX_ENV=py26-dj16-sqlite-nose
    - TOX_ENV=py26-dj16-postgres-unittest
    - TOX_ENV=py26-dj16-postgres-nose
    - TOX_ENV=py26-dj16-mysql-unittest
    - TOX_ENV=py26-dj16-mysql-nose
    - TOX_ENV=py27-dj16-sqlite-unittest
    - TOX_ENV=py27-dj16-sqlite-nose
    - TOX_ENV=py27-dj16-postgres-unittest
    - TOX_ENV=py27-dj16-postgres-nose
    - TOX_ENV=py27-dj16-mysql-unittest
    - TOX_ENV=py27-dj16-mysql-nose
    - TOX_ENV=py27-dj17-sqlite-unittest
    - TOX_ENV=py27-dj17-sqlite-nose
    - TOX_ENV=py27-dj17-postgres-unittest
    - TOX_ENV=py27-dj17-postgres-nose
    - TOX_ENV=py27-dj17-mysql-unittest
    - TOX_ENV=py27-dj17-mysql-nose
    - TOX_ENV=py27-dj18-sqlite-unittest
    - TOX_ENV=py27-dj18-sqlite-nose
    - TOX_ENV=py27-dj18-postgres-unittest
    - TOX_ENV=py27-dj18-postgres-nose
    - TOX_ENV=py27-dj18-mysql-unittest
    - TOX_ENV=py27-dj18-mysql-nose
    - TOX_ENV=py27-dj19-sqlite-unittest
    - TOX_ENV=py27-dj19-sqlite-nose
    - TOX_ENV=py27-dj19-postgres-unittest
    - TOX_ENV=py27-dj19-postgres-nose
    - TOX_ENV=py27-dj19-mysql-unittest
    - TOX_ENV=py27-dj19-mysql-nose
    - TOX_ENV=py27-djmaster-sqlite-unittest
    - TOX_ENV=py27-djmaster-sqlite-nose
    - TOX_ENV=py27-djmaster-postgres-unittest
    - TOX_ENV=py27-djmaster-postgres-nose
    - TOX_ENV=py27-djmaster-mysql-unittest
    - TOX_ENV=py27-djmaster-mysql-nose
    - TOX_ENV=py32-dj16-sqlite-unittest
    - TOX_ENV=py32-dj16-sqlite-nose
    - TOX_ENV=py32-dj16-postgres-unittest
    - TOX_ENV=py32-dj16-postgres-nose
    - TOX_ENV=py32-dj16-mysql-unittest
    - TOX_ENV=py32-dj16-mysql-nose
    - TOX_ENV=py32-dj17-sqlite-unittest
    - TOX_ENV=py32-dj17-sqlite-nose
    - TOX_ENV=py32-dj17-postgres-unittest
    - TOX_ENV=py32-dj17-postgres-nose
    - TOX_ENV=py32-dj17-mysql-unittest
    - TOX_ENV=py32-dj17-mysql-nose
    - TOX_ENV=py32-dj18-sqlite-unittest
    - TOX_ENV=py32-dj18-sqlite-nose
    - TOX_ENV=py32-dj18-postgres-unittest
    - TOX_ENV=py32-dj18-postgres-nose
    - TOX_ENV=py32-dj18-mysql-unittest
    - TOX_ENV=py32-dj18-mysql-nose
    - TOX_ENV=py32-dj19-sqlite-unittest
    - TOX_ENV=py32-dj19-sqlite-nose
    - TOX_ENV=py32-dj19-postgres-unittest
    - TOX_ENV=py32-dj19-postgres-nose
    - TOX_ENV=py32-dj19-mysql-unittest
    - TOX_ENV=py32-dj19-mysql-nose
    - TOX_ENV=py32-djmaster-sqlite-unittest
    - TOX_ENV=py32-djmaster-sqlite-nose
    - TOX_ENV=py32-djmaster-postgres-unittest
    - TOX_ENV=py32-djmaster-postgres-nose
    - TOX_ENV=py32-djmaster-mysql-unittest
    - TOX_ENV=py32-djmaster-mysql-nose
    - TOX_ENV=py33-dj16-sqlite-unittest
    - TOX_ENV=py33-dj16-sqlite-nose
    - TOX_ENV=py33-dj16-postgres-unittest
    - TOX_ENV=py33-dj16-postgres-nose
    - TOX_ENV=py33-dj16-mysql-unittest
    - TOX_ENV=py33-dj16-mysql-nose
    - TOX_ENV=py33-dj17-sqlite-unittest
    - TOX_ENV=py33-dj17-sqlite-nose
    - TOX_ENV=py33-dj17-postgres-unittest
    - TOX_ENV=py33-dj17-postgres-nose
    - TOX_ENV=py33-dj17-mysql-unittest
    - TOX_ENV=py33-dj17-mysql-nose
    - TOX_ENV=py33-dj18-sqlite-unittest
    - TOX_ENV=py33-dj18-sqlite-nose
    - TOX_ENV=py33-dj18-postgres-unittest
    - TOX_ENV=py33-dj18-postgres-nose
    - TOX_ENV=py33-dj18-mysql-unittest
    - TOX_ENV=py33-dj18-mysql-nose
    - TOX_ENV=py33-dj19-sqlite-unittest
    - TOX_ENV=py33-dj19-sqlite-nose
    - TOX_ENV=py33-dj19-postgres-unittest
    - TOX_ENV=py33-dj19-postgres-nose
    - TOX_ENV=py33-dj19-mysql-unittest
    - TOX_ENV=py33-dj19-mysql-nose
    - TOX_ENV=py33-djmaster-sqlite-unittest
    - TOX_ENV=py33-djmaster-sqlite-nose
    - TOX_ENV=py33-djmaster-postgres-unittest
    - TOX_ENV=py33-djmaster-postgres-nose
    - TOX_ENV=py33-djmaster-mysql-unittest
    - TOX_ENV=py33-djmaster-mysql-nose
    - TOX_ENV=py34-dj16-sqlite-unittest
    - TOX_ENV=py34-dj16-sqlite-nose
    - TOX_ENV=py34-dj16-postgres-unittest
    - TOX_ENV=py34-dj16-postgres-nose
    - TOX_ENV=py34-dj16-mysql-unittest
    - TOX_ENV=py34-dj16-mysql-nose
    - TOX_ENV=py34-dj17-sqlite-unittest
    - TOX_ENV=py34-dj17-sqlite-nose
    - TOX_ENV=py34-dj17-postgres-unittest
    - TOX_ENV=py34-dj17-postgres-nose
    - TOX_ENV=py34-dj17-mysql-unittest
    - TOX_ENV=py34-dj17-mysql-nose
    - TOX_ENV=py34-dj18-sqlite-unittest
    - TOX_ENV=py34-dj18-sqlite-nose
    - TOX_ENV=py34-dj18-postgres-unittest
    - TOX_ENV=py34-dj18-postgres-nose
    - TOX_ENV=py34-dj18-mysql-unittest
    - TOX_ENV=py34-dj18-mysql-nose
    - TOX_ENV=py34-dj19-sqlite-unittest
    - TOX_ENV=py34-dj19-sqlite-nose
    - TOX_ENV=py34-dj19-postgres-unittest
    - TOX_ENV=py34-dj19-postgres-nose
    - TOX_ENV=py34-dj19-mysql-unittest
    - TOX_ENV=py34-dj19-mysql-nose
    - TOX_ENV=py34-djmaster-sqlite-unittest
    - TOX_ENV=py34-djmaster-sqlite-nose
    - TOX_ENV=py34-djmaster-postgres-unittest
    - TOX_ENV=py34-djmaster-postgres-nose
    - TOX_ENV=py34-djmaster-mysql-unittest
    - TOX_ENV=py34-djmaster-mysql-nose
    - TOX_ENV=py35-dj16-sqlite-unittest
    - TOX_ENV=py35-dj16-sqlite-nose
    - TOX_ENV=py35-dj16-postgres-unittest
    - TOX_ENV=py35-dj16-postgres-nose
    - TOX_ENV=py35-dj16-mysql-unittest
    - TOX_ENV=py35-dj16-mysql-nose
    - TOX_ENV=py35-dj17-sqlite-unittest
    - TOX_ENV=py35-dj17-sqlite-nose
    - TOX_ENV=py35-dj17-postgres-unittest
    - TOX_ENV=py35-dj17-postgres-nose
    - TOX_ENV=py35-dj17-mysql-unittest
    - TOX_ENV=py35-dj17-mysql-nose
    - TOX_ENV=py35-dj18-sqlite-unittest
    - TOX_ENV=py35-dj18-sqlite-nose
    - TOX_ENV=py35-dj18-postgres-unittest
    - TOX_ENV=py35-dj18-postgres-nose
    - TOX_ENV=py35-dj18-mysql-unittest
    - TOX_ENV=py35-dj18-mysql-nose
    - TOX_ENV=py35-dj19-sqlite-unittest
    - TOX_ENV=py35-dj19-sqlite-nose
    - TOX_ENV=py35-dj19-postgres-unittest
    - TOX_ENV=py35-dj19-postgres-nose
    - TOX_ENV=py35-dj19-mysql-unittest
    - TOX_ENV=py35-dj19-mysql-nose
    - TOX_ENV=py35-djmaster-sqlite-unittest
    - TOX_ENV=py35-djmaster-sqlite-nose
    - TOX_ENV=py35-djmaster-postgres-unittest
    - TOX_ENV=py35-djmaster-postgres-nose
    - TOX_ENV=py35-djmaster-mysql-unittest
    - TOX_ENV=py35-djmaster-mysql-nose

matrix:
  fast_finish: true
  allow_failures:
    - env: TOX_ENV=py27-djmaster-sqlite-unittest
    - env: TOX_ENV=py27-djmaster-sqlite-nose
    - env: TOX_ENV=py27-djmaster-postgres-unittest
    - env: TOX_ENV=py27-djmaster-postgres-nose
    - env: TOX_ENV=py27-djmaster-mysql-unittest
    - env: TOX_ENV=py27-djmaster-mysql-nose
    - env: TOX_ENV=py32-dj16-mysql-unittest
    - env: TOX_ENV=py32-dj16-mysql-nose
    - env: TOX_ENV=py32-dj17-mysql-unittest
    - env: TOX_ENV=py32-dj17-mysql-nose
    - env: TOX_ENV=py32-dj18-mysql-unittest
    - env: TOX_ENV=py32-dj18-mysql-nose
    - env: TOX_ENV=py32-dj19-sqlite-unittest
    - env: TOX_ENV=py32-dj19-sqlite-nose
    - env: TOX_ENV=py32-dj19-postgres-unittest
    - env: TOX_ENV=py32-dj19-postgres-nose
    - env: TOX_ENV=py32-dj19-mysql-unittest
    - env: TOX_ENV=py32-dj19-mysql-nose
    - env: TOX_ENV=py32-djmaster-sqlite-unittest
    - env: TOX_ENV=py32-djmaster-sqlite-nose
    - env: TOX_ENV=py32-djmaster-postgres-unittest
    - env: TOX_ENV=py32-djmaster-postgres-nose
    - env: TOX_ENV=py32-djmaster-mysql-unittest
    - env: TOX_ENV=py32-djmaster-mysql-nose
    - env: TOX_ENV=py33-dj19-sqlite-unittest
    - env: TOX_ENV=py33-dj19-sqlite-nose
    - env: TOX_ENV=py33-dj19-postgres-unittest
    - env: TOX_ENV=py33-dj19-postgres-nose
    - env: TOX_ENV=py33-dj19-mysql-unittest
    - env: TOX_ENV=py33-dj19-mysql-nose
    - env: TOX_ENV=py33-djmaster-sqlite-unittest
    - env: TOX_ENV=py33-djmaster-sqlite-nose
    - env: TOX_ENV=py33-djmaster-postgres-unittest
    - env: TOX_ENV=py33-djmaster-postgres-nose
    - env: TOX_ENV=py33-djmaster-mysql-unittest
    - env: TOX_ENV=py33-djmaster-mysql-nose
    - env: TOX_ENV=py34-djmaster-sqlite-unittest
    - env: TOX_ENV=py34-djmaster-sqlite-nose
    - env: TOX_ENV=py34-djmaster-postgres-unittest
    - env: TOX_ENV=py34-djmaster-postgres-nose
    - env: TOX_ENV=py34-djmaster-mysql-unittest
    - env: TOX_ENV=py34-djmaster-mysql-nose
    - env: TOX_ENV=py35-dj16-sqlite-unittest
    - env: TOX_ENV=py35-dj16-sqlite-nose
    - env: TOX_ENV=py35-dj16-postgres-unittest
    - env: TOX_ENV=py35-dj16-postgres-nose
    - env: TOX_ENV=py35-dj16-mysql-unittest
    - env: TOX_ENV=py35-dj16-mysql-nose
    - env: TOX_ENV=py35-dj17-sqlite-unittest
    - env: TOX_ENV=py35-dj17-sqlite-nose
    - env: TOX_ENV=py35-dj17-postgres-unittest
    - env: TOX_ENV=py35-dj17-postgres-nose
    - env: TOX_ENV=py35-dj17-mysql-unittest
    - env: TOX_ENV=py35-dj17-mysql-nose
    - env: TOX_ENV=py35-dj18-sqlite-unittest
    - env: TOX_ENV=py35-dj18-sqlite-nose
    - env: TOX_ENV=py35-dj18-postgres-unittest
    - env: TOX_ENV=py35-dj18-postgres-nose
    - env: TOX_ENV=py35-dj18-mysql-unittest
    - env: TOX_ENV=py35-dj18-mysql-nose
    - env: TOX_ENV=py35-dj19-sqlite-unittest
    - env: TOX_ENV=py35-dj19-sqlite-nose
    - env: TOX_ENV=py35-dj19-postgres-unittest
    - env: TOX_ENV=py35-dj19-postgres-nose
    - env: TOX_ENV=py35-dj19-mysql-unittest
    - env: TOX_ENV=py35-dj19-mysql-nose
    - env: TOX_ENV=py35-djmaster-sqlite-unittest
    - env: TOX_ENV=py35-djmaster-sqlite-nose
    - env: TOX_ENV=py35-djmaster-postgres-unittest
    - env: TOX_ENV=py35-djmaster-postgres-nose
    - env: TOX_ENV=py35-djmaster-mysql-unittest
    - env: TOX_ENV=py35-djmaster-mysql-nose

before_install:
  - pip install codecov

install:
  - pip install -r requirements-test.txt

script:
  - tox -e $TOX_ENV

after_success:
  - coverage run --source django_fake_model runtests.py
  - codecov
